version: '3'
services:
  philter:
    environment:
      - PHILTER_LICENSE_KEY=asdf
      - PHILTER_NER_ENDPOINT=http://philter-ner:18080/
    image: mtnfog/philter:1.6.0-SNAPSHOT
    links:
      - philter-ner
    networks:
      - philter
    ports:
      - "8080:8080"
  philter-ner:
    image: mtnfog/philter-ner:1.5.0.914.a26bb36
    networks:
      - philter
    ports:
      - "18080:18080"
networks:
  philter:
    driver: "bridge"
