version: '3'
services:
  philter:
    environment:
      - PHILTER_LICENSE_KEY=
      - PHILTER_NER_ENDPOINT=http://philter-ner:18080/
    image: docker.mtnfog.com/philter:1.7.0
    links:
      - philter-ner
    networks:
      - philter
    ports:
      - "8080:8080"
  philter-ner:
    image: docker.mtnfog.com/philter-ner:1.7.0
    networks:
      - philter
    ports:
      - "18080:18080"
networks:
  philter:
    driver: "bridge"
